### PR TITLE
Added Discord Chat

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SwadicalRag** [comment]
can we please merge this already

there's no reason why we are putting this off

**Comment by LennyPenny** [comment]
imagine using discord lmao

**Comment by SwadicalRag** [comment]
ur all lame
no exceptions

**Comment by HandsomeMatt** [comment]
I think the only lame people are those that use Discord

**Comment by SpencerSharkey** [comment]
Discord is for idiots tbh What's wrong with steam

**Comment by SpencerSharkey** [comment]
Doesn't anyone know the owner of discord previously sold off a company to escape the legal battle after he sold all his user's private info? Yeah. Also, how long do you think it'll be completely free? Yeah. GG discord.

**Comment by gspetrou** [comment]
Can we just use Skype.

**Comment by GuurgleOS** [comment]
Updated link (because someone deleted it :<) and squashed commits.

**Comment by HandsomeMatt** [comment]
ooooOoooO discord haha wankers

**Comment by SwadicalRag** [comment]
mate

**Pull request closed without merging**
